### ISSUE TITLE
SMP over asynchronous notifications

### ISSUE THREAD

**Issue by BikeBr0** [jkdhn/mcumgr-dart#4]
What is the best way to receive SMP Messages through notifications? I have a device that cannot respond to a custom command synchronously and instead eventually responds through a notification.  Thanks!

**Comment by jkdhn** [comment]
Devices can only send exactly one response for each request, there is no mechanism for notifications from the device. Instead, the client could periodically send a request to poll for the result.

If it doesn't take too long, you could just do it synchronously, but you probably can't execute other commands while still waiting for the response (mcumgr-dart allows this, but devices usually queue incoming requests and process them one at a time).

**Comment by BikeBr0** [comment]
That's been my experience too. The problem we have is that the device needs considerable time to gather the data for the response (and will block other commands), so instead it responds quickly with an empty response and a few seconds later sends a notification with the actual data.

The ability to send SMP notifications was recently added to the MCUMGR implementation on Zephyr:

https://github.com/zephyrproject-rtos/zephyr/blob/af98ca076b646ade6a83bd563bdd92e59fc0fe97/include/zephyr/mgmt/mcumgr/smp_bt.h (commit: https://github.com/zephyrproject-rtos/zephyr/commit/e8280097577d9d3e20c1eb7fd734b6993c6c8850)

It would be handy if we could register a listener when creating the client. Something like:

`
client.notifications.listen({
    prop1: value1,
    prop2: value2,
    prop3: value3
});
`

Is this feasible. What do you think?

**Comment by jkdhn** [comment]
Currently, decoded packets are published to a broadcast stream (`_input`). When executing a request, we wait for the next response with the matching sequence number and packet type:
https://github.com/jkdhn/mcumgr-dart/blob/43a69a7ebdb85d889828d5599d90dd9ec8d7811d/lib/client.dart#L49-L53

The author of the commit you mentioned is apparently using a non-standard `notify` packet type:
https://github.com/LairdCP/Attributes/blob/3394a1e2670253d3980f8473990f1012912a826a/universal/source/attribute_mgmt.c#L263

I would prefer not to add non-standard features to this library, so maybe this could work instead:
* Expose the `_input` stream (would be nice to have for stuff like debug logging anyways)
* Allow undefined packet types here (store int instead of PacketType): https://github.com/jkdhn/mcumgr-dart/blob/43a69a7ebdb85d889828d5599d90dd9ec8d7811d/lib/src/mgmt/header.dart#L28

Then you could just subscribe to something like `client.incoming.where((m) => m.header.type == 4)`.

**Comment by BikeBr0** [comment]
I think that will work. If I understand correctly, I would subscribe to the notification when my screen initializes, issue the command (throw away the direct response to the command) and have my notification subscriber handle the message. Probably add a timeout feature that displays an error if a notification message is not received.

**Comment by BikeBr0** [comment]
If an SMP Message requires multiple notifications (because it is so large) will this be handled transparently to me and arrive as a single Message?

**Comment by jkdhn** [comment]
The client already reassembles fragmented incoming messages: https://github.com/jkdhn/mcumgr-dart/blob/43a69a7ebdb85d889828d5599d90dd9ec8d7811d/lib/src/smp/smp.dart#L24-L45

You will have to make sure you don't send anything else concurrently while sending a fragmented message.

> I think that will work. If I understand correctly, I would subscribe to the notification when my screen initializes, issue the command (throw away the direct response to the command) and have my notification subscriber handle the message. Probably add a timeout feature that displays an error if a notification message is not received.

That sounds good. I'll probably have time to implement the needed changes for this tomorrow.

**Comment by jkdhn** [comment]
I've added `client.incoming`, `client.outgoing` and `client.send`. Those methods use `Packet` instead of `Message`, so you need to do the CBOR encoding/decoding yourself (`cbor.encode(...)`, `cbor.decode(...) as CborMap`).
There's no release with this yet, so for now you will have to depend on it [using Git](https://dart.dev/tools/pub/dependencies#git-packages).

**Comment by BikeBr0** [comment]
This worked great. Here is a code snippet of my implementation (for review and for future developers looking for a recipe);

```
  /// Regular method for a synchronous read operation on a device
  Future<Map> readSettings(MACAddress address, Duration timeout) async {
    final message = await execute(
      Message(
        op: Operation.read,
        group: _smpGroup,
        id: _getDevState,
        flags: 0,
        data: CborMap({
          CborValue('p1'): CborBytes(address.bytes),
          CborValue('p2'): CborString('ble')
        }),
      ),
      timeout,
    );
    
    String response = (message.data[CborString("s")] as CborString).toString(allowMalformed: true);
    final data = response.isNotEmpty ? jsonDecode(response) : {};
    return data['data'] ?? {};
  }

  /// Async method for a read operation on a device
  Future<Map> readSettingsAsync(MACAddress address, Duration timeout) async {

    final Future<Map> future = incoming
            .where((packet) => packet.header.sequence == 0)
            .map<Message>((packet) {
              return Message(
                op: packet.header.type,
                group: packet.header.group,
                id: packet.header.id,
                flags: packet.header.flags,
                data: cbor.decode(packet.content) as CborMap
              );
            })
            .map<Map>((message) {
              String response = (message.data[CborString("s")] as CborString).toString(allowMalformed: true);
              final data = response.isNotEmpty ? jsonDecode(response) : {};
              return data['data'] ?? {};
            })
            .first;
    
    future.timeout(
      timeout,
      onTimeout: () => throw TimeoutException('No response within ${timeout.inSeconds}s')
    );

    /// Call the regular (synchronous) command and ignore the empty response since the actual data will come 
    /// through a notification
    readSettings(address, timeout);

    return future;
  }
```
